<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/**
 * Adds the `attendance_method` column to `attendance_records`.
 *
 * Allowed values:
 *   scan   – recorded via Student ID / barcode scan
 *   manual – recorded manually by the instructor
 *   system – automatically generated by the system (e.g. Absent at session close)
 *
 * Strategy for existing data:
 *   - Default is 'system' (safest — does not misrepresent any record as a new scan).
 *   - After adding the column we back-fill existing present/late records as 'scan',
 *     since those could only have come from the scan workflow.
 *   - Existing absent records (scanned_at IS NULL) remain 'system'.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::table('attendance_records', function (Blueprint $table) {
            $table->string('attendance_method')
                ->default('system')
                ->after('scanned_at')
                ->comment('scan | manual | system');
        });

        // Back-fill: any present/late record that has a scanned_at timestamp
        // was created through the scan workflow.
        DB::table('attendance_records')
            ->whereNotNull('scanned_at')
            ->whereIn('status', ['present', 'late'])
            ->update(['attendance_method' => 'scan']);
    }

    public function down(): void
    {
        Schema::table('attendance_records', function (Blueprint $table) {
            $table->dropColumn('attendance_method');
        });
    }
};
