<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class AttendanceRecord extends Model
{
    protected $fillable = [
        'attendance_session_id',
        'student_id',
        'status',
        'scanned_at',
        'attendance_method',
    ];

    protected $casts = [
        'scanned_at' => 'datetime',
    ];

    // ── Attendance status constants ────────────────────────────────────────────
    const STATUS_PRESENT = 'present';
    const STATUS_LATE    = 'late';
    const STATUS_ABSENT  = 'absent';

    // ── Attendance method constants ────────────────────────────────────────────
    /** Recorded via Student ID / barcode scan. */
    const METHOD_SCAN   = 'scan';

    /** Recorded manually by the instructor (no ID presented). */
    const METHOD_MANUAL = 'manual';

    /** Automatically generated by the system (e.g. Absent at session close). */
    const METHOD_SYSTEM = 'system';

    // ── Relationships ──────────────────────────────────────────────────────────

    public function session()
    {
        return $this->belongsTo(AttendanceSession::class, 'attendance_session_id');
    }

    public function student()
    {
        return $this->belongsTo(Student::class);
    }
}
